(() => {
const api=(window.EDUCRAFT_API_BASE_URL||"").replace(/\/$/,""); const token=localStorage.getItem("educraft.dashboard.accessToken")||""; const main=document.querySelector("#studentMain");
let overview=null, activities=[];
const esc=(s)=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function req(path){const r=await fetch(api+path,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"}});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.message||`HTTP ${r.status}`)}return r.json()}
function logout(){["accessToken","refreshToken","expiresAt"].forEach(k=>localStorage.removeItem(`educraft.dashboard.${k}`));location.replace("login.html")}
function task(item,action=false){const programming=["scratch","web"].includes(item.programmingMode);const state=item.projectStatus==="submitted"?"Entregada":item.projectStatus?"En progreso":programming?"Pendiente":"Actividad de aula"; const link=programming?`../programacion/?activity=${encodeURIComponent(item.id)}&return=${encodeURIComponent(location.href)}`:"";return `<article class="task"><h3>${esc(item.title)}</h3><p>${esc(item.subject)} · ${esc(item.level)} · ${item.durationMinutes} min</p><p>${esc(item.objectives)}</p><div class="task-footer"><span class="status">${state}</span>${action&&programming?`<a class="student-button" href="${link}">${item.projectStatus==="submitted"?"Ver proyecto":"Abrir programación"}</a>`:""}</div></article>`}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
function render(view){document.querySelectorAll("[data-view]").forEach(a=>a.classList.toggle("active",a.dataset.view===view));const name=overview.email?.split("@")[0]||"";const tasks=activities.map(a=>task(a,true)).join("")||empty("No hay actividades publicadas para ti ahora mismo.");
let body="";
if(view==="inicio")body=`<section class="student-hero"><div><h1>Hola, ${esc(name)}</h1><p>Este es tu espacio académico. Las actividades del mundo se muestran aquí para que sigas tu progreso, pero se realizan en el cliente EduCraft.</p></div></section><section class="student-grid"><article class="student-card metric"><strong>${overview.metrics.availableActivities||0}</strong><span>actividades disponibles</span></article><article class="student-card metric"><strong>${overview.metrics.programmingInProgress||0}</strong><span>proyectos en progreso</span></article><article class="student-card metric"><strong>${overview.metrics.programmingSubmitted||0}</strong><span>proyectos entregados</span></article></section><section class="student-card" style="margin-top:16px"><h2>Actividad reciente</h2><div class="task-list">${overview.recent.map(a=>task(a,true)).join("")||empty("Todavía no tienes actividad reciente.")}</div></section>`;
else if(view==="tareas")body=`<section class="student-hero"><div><h1>Tareas</h1><p>Solo ves las actividades publicadas por tu centro. Las de programación se completan desde este portal.</p></div></section><section class="task-list">${tasks}</section>`;
else if(view==="programacion")body=`<section class="student-hero"><div><h1>Programación</h1><p>Tu único entorno oficial de programación. Guarda, prueba y entrega tus proyectos aquí.</p></div></section><section class="task-list">${activities.filter(a=>["scratch","web"].includes(a.programmingMode)).map(a=>task(a,true)).join("")||empty("No tienes ejercicios de bloques o web publicados.")}</section>`;
else if(view==="progreso")body=`<section class="student-hero"><div><h1>¿Cómo voy?</h1><p>Estas cifras proceden solo de tus proyectos de programación.</p></div></section><section class="student-grid"><article class="student-card metric"><strong>${overview.metrics.programmingInProgress||0}</strong><span>en progreso</span></article><article class="student-card metric"><strong>${overview.metrics.programmingSubmitted||0}</strong><span>entregados</span></article></section>`;
else if(view==="perfil")body=`<section class="student-hero"><div><h1>Perfil</h1><p>Tu información académica se administra desde el centro.</p></div></section><section class="student-card"><h2>Información</h2><p><strong>Correo:</strong> ${esc(overview.email)}</p><p><strong>Curso:</strong> ${esc(overview.course||"No disponible")}</p><p><strong>Grupo:</strong> ${esc(overview.classGroup||"No disponible")}</p></section>`;
else body=`<section class="student-hero"><div><h1>${view==="inventario"?"Inventario y recompensas":"Recomendaciones"}</h1><p>Mostraremos información personal cuando exista una fuente vinculada de forma segura a tu cuenta.</p></div></section>${empty(view==="inventario"?"Todavía no hay recompensas académicas vinculadas a tu perfil.":"Todavía no hay recomendaciones personalizadas disponibles.")}`;
main.innerHTML=body}
async function boot(){if(!token){logout();return}try{const me=await req("/me");if(me.role!=="student"){location.replace(me.role==="teacher"?"profesor-clases.html":"login.html");return}const results=await Promise.all([req("/dashboard/student/overview"),req("/dashboard/student/activities")]);overview=results[0];activities=results[1].items||[];const show=()=>render(location.hash.slice(1)||"inicio");addEventListener("hashchange",show);show()}catch(e){main.innerHTML=`<div class="empty">No se pudo cargar tu espacio: ${esc(e.message)}. Comprueba tu conexión e inténtalo de nuevo.</div>`}}
document.querySelector("#studentLogout").addEventListener("click",logout);boot();
})();
